pipelines:
  mst-user-service:
    group: mst
    label_template: "${COUNT}"
    locking: off
    # setting materials
    materials:
      app:
        git: https://github.com/hui000444/mst-user-service.git
        branch: master
    # setting stages
    stages:
      - test:
          clean_workspace: true
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/test.sh"
                    run_if: passed
      - build:
          clean_workspace: yes
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/build.sh"
                    run_if: passed
      - deploy:
          clean_workspace: yes
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/deploy.sh"
                    run_if: passed
