pipelines:
  mst-config-service:
    group: mst
    label_template: "${COUNT}"
    locking: off
    # setting materials
    materials:
      app:
        git: https://github.com/hui000444/mst-config-server
        branch: master
    # setting stages
    stages:
      - build:
          clean_workspace: yes
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/build.sh"
                    run_if: passed
      - deploy:
          clean_workspace: yes
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/deploy.sh"
                    run_if: passed
